application: kegmate
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /user/.*
  script: user_actions.app

- url: /beer/.*
  script: beer_actions.app

- url: /taps/.*
  script: tap_actions.app

- url: /tap/.*
  script: tap_actions.app

libraries:
- name: webapp2
  version: "2.5.1"
